name: Code Check React TS
run-name: code check React TS - \#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  CheckCodeReact:
    name: check react ts code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: install dependencies
        working-directory: ./react-app
        run: |
          npm ci
      - name: lint code
        working-directory: ./react-app
        run: |
          npm run lint
      - name: build code
        working-directory: ./react-app
        run: |
          npm run build
